FROM nvidia/cuda:11.7.1-runtime-ubuntu20.04

RUN apt-get update -y && apt-get install -y python3.9 python3.9-distutils curl git
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.9 get-pip.py

RUN git clone -b controller-only https://github.com/RWolfing/FastChat.git

WORKDIR FastChat
RUN pip3 install --upgrade pip
RUN pip3 install -e .

CMD python3.9 -m fastchat.serve.controller \
     --host 0.0.0.0 \
     --port 8000
