FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install -y python3.9 python3.9-distutils curl git && \
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3.9 get-pip.py

RUN pip3 install fschat
    
RUN groupadd -r fastchat && useradd -r -g fastchat -u 1001 fastchat

RUN mkdir /app && chown fastchat:fastchat /app

WORKDIR /app

USER fastchat:fastchat

RUN unset DEBIAN_FRONTEND

EXPOSE 8000

CMD ["python3.9", "-m", "fastchat.serve.openai_api_server", "--controller-address", "https://woven-fschat.cityos-dev.woven-planet.tech", "--host", "0.0.0.0", "--port", "8000"]
