FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install -y python3.9 python3.9-distutils curl git && \
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3.9 get-pip.py

RUN git clone https://github.com/RWolfing/FastChat.git

WORKDIR FastChat
RUN pip3 install --upgrade pip && \
    pip3 install -e .

RUN unset DEBIAN_FRONTEND

CMD ["python3.9", "-m", "fastchat.serve.controller", "--host", "0.0.0.0", "--port", "8000"]
