FROM python:3.9-slim

RUN pip3 install fschat
    
RUN groupadd -r fastchat && useradd -r -g fastchat -u 1001 fastchat

RUN mkdir /app && chown fastchat:fastchat /app

WORKDIR /app

USER fastchat:fastchat

EXPOSE 8000

ENV CONTROLLER_ADDRESS=http://localhost:21001
ENV PROPS=""

CMD python3.9 -m fastchat.serve.openai_api_server \
     --controller-address $CONTROLLER_ADDRESS \
     --host 0.0.0.0 \
     --port 8000 \
     ${PROPS:+$PROPS}
